### PR TITLE
Add more clickable alternative to the cursed irc uri

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Comment by ChillerDragon** [comment]
true gigachads use https://chat.zillyhuhn.com/ of course

**Comment by Matodor** [comment]
Maybe use `https://webchat.quakenet.org/?channels=teeworlds` ?

**Comment by Matodor** [comment]
> true gigachads use https://chat.zillyhuhn.com/ of course

I think this could be added to the "Projects" section, with a link to the website and source code.

**Comment by ChillerDragon** [comment]
> Maybe use `https://webchat.quakenet.org/?channels=teeworlds` ?

Cool I always was wondering if that works. I assumed since the url is not updated automatically when filling out the form it does not exist.

**Comment by ChillerDragon** [comment]
> I think this could be added to the "Projects" section, with a link to the website and source code.

The code is here https://github.com/discord-irc/discord-irc and I use it actively. But it is not teeworlds related nor guaranteed  to be friendly to users other than ChillerDragon. Also it might go down in 2 years who knows.

It was more of a joke from my side :D the thing is just a weird crappy irc client and not really a tw project.

**Pull request merged**
